/**
 * Build-time generator for the installable component-registry source map.
 *
 * Vercel's serverless runtime can't read `.tsx` source files from disk, so we
 * embed the raw TSX at build time into a committed `lib/magic/registry-source.ts`
 * that Next bundles. `/api/registry` then serves it as real shadcn-installable
 * `files[]` when `componentRegistryShipsSource` is on.
 *
 * Scope: a CURATED allowlist of self-contained, MIT-licensed presentational
 * atoms. For each, we include the atom file + its 1-level local `./Sibling`
 * imports (e.g. StudioSection). Project-level imports (`@/lib/utils` cn,
 * next/link, zod) are left as-is — consumers resolve them via their shadcn `@/`
 * alias, the standard registry convention.
 *
 * Run: `pnpm build:registry` (wired into `pnpm build`). Regenerate when a
 * shipped atom or its deps change.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const SECTIONS_DIR = join(ROOT, "designs/studio/sections");

/** sectionKey → component filename. Only fully self-contained presentational atoms. */
const ALLOWLIST: Record<string, string> = {
  testimonials: "StudioTestimonials.tsx",
  faq: "StudioFaq.tsx",
  pricingTable: "StudioPricingTable.tsx",
  statBand: "StudioStatBand.tsx",
  logoCloud: "StudioLogoCloud.tsx",
  galleryGrid: "StudioGalleryGrid.tsx",
  bannerCta: "StudioBannerCta.tsx",
  quote: "StudioQuote.tsx",
};

/** Local `from "./X"` sibling imports → `X.tsx` filenames (one level). */
function localSiblings(content: string): string[] {
  const out = new Set<string>();
  const re = /from\s+"\.\/([A-Za-z0-9_-]+)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(content)) !== null) out.add(`${m[1]}.tsx`);
  return [...out];
}

type FileEntry = { path: string; content: string; type: string };
type Entry = { files: FileEntry[]; registryDependencies: string[] };

const map: Record<string, Entry> = {};

for (const [key, file] of Object.entries(ALLOWLIST)) {
  const seen = new Set<string>();
  const files: FileEntry[] = [];
  const queue = [file];
  while (queue.length) {
    const f = queue.shift() as string;
    if (seen.has(f)) continue;
    seen.add(f);
    let content: string;
    try {
      content = readFileSync(join(SECTIONS_DIR, f), "utf8");
    } catch {
      continue; // missing sibling → skip (best-effort)
    }
    files.push({ path: `components/cartwright/${f}`, content, type: "registry:component" });
    for (const sib of localSiblings(content)) queue.push(sib);
  }
  map[key] = { files, registryDependencies: [] };
}

const banner = `// AUTO-GENERATED by scripts/build-registry-source.ts — DO NOT EDIT.
// Run \`pnpm build:registry\` to regenerate. Raw TSX for the curated, installable
// subset of section atoms served by /api/registry when componentRegistryShipsSource is on.
`;

const out = `${banner}
export type RegistrySourceEntry = {
  files: { path: string; content: string; type: string }[];
  registryDependencies: string[];
};

export const REGISTRY_SOURCE_MAP: Record<string, RegistrySourceEntry> = ${JSON.stringify(map, null, 2)};
`;

writeFileSync(join(ROOT, "lib/magic/registry-source.ts"), out, "utf8");
console.log(
  `[build-registry-source] wrote ${Object.keys(map).length} entries (${Object.values(map).reduce((n, e) => n + e.files.length, 0)} files)`,
);
