#!/bin/bash
# scripts/verify-deploy.sh <url>
#
# Answers one question a green deploy cannot: **did the app actually get built,
# or is the platform serving a directory?**
#
# A deploy can report success and serve nothing. The way it happens on Vercel is
# documented, not exotic: a project whose Framework Preset is "Other" — which is
# what you get when the project is created empty from the CLI rather than
# imported from a repo — sets "the output directory as `public` if it exists or
# `.` otherwise". Cartwright HAS a public/ directory. So the platform skips
# `next build` and serves your logos as a static site. Every route 404s, the
# build log is empty, nothing errors, and the dashboard says Ready.
#
# ## Why these three paths
#
# `/robots.txt`, `/sitemap.xml` and `/llms.txt` are GENERATED by the app
# (app/robots.ts, app/sitemap.ts, app/llms.txt/route.ts) and do NOT exist as
# files in public/. That is the whole point: they can only answer 200 if the
# framework actually ran.
#
# The trap this avoids: `public/mcp.json` WOULD return 200 in exactly the broken
# state above. A check that asks "does some URL respond?" passes straight
# through the failure. Only a generated route distinguishes "built" from
# "served".
#
# ## Usage
#
#   pnpm verify:deploy https://your-shop.example
#   bash scripts/verify-deploy.sh https://your-shop.example
#
# Exits 0 when every route answers 200, 1 otherwise. Safe to run against any
# deployment — it only issues GETs.

set -u

URL="${1:-}"
if [ -z "$URL" ]; then
  echo "usage: bash scripts/verify-deploy.sh <deployment-url>" >&2
  echo "   eg: bash scripts/verify-deploy.sh https://your-shop.vercel.app" >&2
  exit 2
fi

# Trailing slashes would produce "//robots.txt" — harmless on most hosts, but
# not on all of them, and a false failure here is worse than useless.
URL="${URL%/}"

# Generated/discovery routes every agent-ready profile advertises.
GENERATED_ROUTES="robots.txt sitemap.xml llms.txt openapi.json developers"
AI_USER_AGENTS="ChatGPT-User ClaudeBot Google-Extended DeepSeekBot ora-agent"
FAIL=0
CHECKS=0

echo "▶ verifying $URL"

for path in $GENERATED_ROUTES; do
  CHECKS=$((CHECKS + 1))
  code=$(curl -sL -o /dev/null -w '%{http_code}' --max-time 30 "$URL/$path" || echo "000")
  if [ "$code" = "200" ]; then
    echo "    /$path: 200 ✓"
  else
    echo "    /$path: $code (expected 200) ✗"
    FAIL=$((FAIL + 1))
  fi
done

echo "▶ verifying AI crawler reachability (redirects followed)"
for user_agent in $AI_USER_AGENTS; do
  CHECKS=$((CHECKS + 1))
  code=$(curl -sL -A "$user_agent" -o /dev/null -w '%{http_code}' --max-time 30 "$URL/" || echo "000")
  if [ "$code" = "200" ]; then
    echo "    $user_agent: 200 ✓"
  else
    echo "    $user_agent: $code (expected 200) ✗"
    FAIL=$((FAIL + 1))
  fi
done

echo "▶ verifying markdown negotiation"
CHECKS=$((CHECKS + 1))
MARKDOWN_HEADERS=$(curl -sLI -H 'Accept: text/markdown' --max-time 30 "$URL/" || true)
if printf '%s' "$MARKDOWN_HEADERS" | grep -qi '^content-type: text/markdown' && \
   printf '%s' "$MARKDOWN_HEADERS" | grep -qi '^vary:.*accept'; then
  echo "    homepage markdown + Vary: Accept ✓"
else
  echo "    homepage markdown negotiation headers missing ✗"
  FAIL=$((FAIL + 1))
fi

if [ $FAIL -eq 0 ]; then
  echo "  ✅ the app is built and serving — $URL"
  exit 0
fi

echo "  ❌ $FAIL/$CHECKS deployment probes failed at $URL"
echo
echo "  These paths are produced by the app, not by files in public/. If they"
echo "  404 while the deploy reports success, the most likely cause is that the"
echo "  build never ran and the platform is serving public/ as a static site."
echo
echo "  On Vercel, check the Framework Preset:"
echo "      vercel project inspect            # 'Other' is the broken state"
echo "      vercel project update --framework nextjs"
echo
echo "  This repo pins it in vercel.json (\"framework\": \"nextjs\"), which"
echo "  overrides the project setting — so also confirm that key survived."
echo
echo "  Reading 'vercel inspect' output: a healthy deploy's Builds tree has λ"
echo "  entries under the root. The [0ms] on the root line is normal and appears"
echo "  on working deploys too — the absence of lambdas is the signal, not the"
echo "  timing."
exit 1
