import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * The two facts that decide whether a successful deploy actually serves the app.
 *
 * A Vercel project whose Framework Preset is "Other" — what you get when the
 * project is created empty from the CLI instead of imported from a repo — sets,
 * per Vercel's own docs, "the output directory as `public` if it exists or `.`
 * otherwise". Cartwright HAS a public/ directory. The platform then skips
 * `next build` and serves the logos as a static site: every route 404s, the
 * build log is empty, nothing errors, and the dashboard says Ready.
 *
 * `vercel.json`'s `framework` key is the fix, and it is stronger than a
 * dashboard setting because it *overrides* one — so it holds no matter how the
 * project was created. It is one line in a file nobody reads, which is exactly
 * the kind of line that gets dropped in a merge. This pins it.
 *
 * The second half is the check that survives being wrong about the first:
 * `scripts/verify-deploy.sh` asks the deployment for routes the APP generates.
 * The subtlety worth protecting is which routes — `public/mcp.json` answers 200
 * in precisely the broken state, so a check aimed at any static file passes
 * straight through the failure it exists to catch. Measured: serving public/
 * with a plain static server returns 404 for all three generated routes and
 * 200 for /mcp.json.
 */

const ROOT = join(__dirname, "..", "..");

describe("vercel.json pins the framework preset", () => {
  const config = JSON.parse(readFileSync(join(ROOT, "vercel.json"), "utf8"));

  it('declares "nextjs" — without it a CLI-created project serves public/ statically', () => {
    expect(config.framework).toBe("nextjs");
  });

  it("does not override outputDirectory (the framework preset already sets it)", () => {
    // Pinning both is how you get a working framework and a wrong output dir.
    expect(config.outputDirectory).toBeUndefined();
  });
});

describe("verify-deploy checks GENERATED routes, not static files", () => {
  const script = join(ROOT, "scripts", "verify-deploy.sh");

  it("ships (it is the only post-deploy check a fork gets)", () => {
    expect(existsSync(script)).toBe(true);
  });

  const source = readFileSync(script, "utf8");
  const routes = source.match(/^GENERATED_ROUTES=.*$/m)?.[0] ?? "";

  it("asks for routes the app produces", () => {
    // Each of these is a route handler, not a file in public/ — so a 200 proves
    // the framework ran. Keep them in sync with app/robots.ts, app/sitemap.ts
    // and app/llms.txt/route.ts.
    for (const path of ["robots.txt", "sitemap.xml", "llms.txt"]) {
      expect(routes, `verify-deploy.sh no longer checks /${path}`).toContain(path);
      expect(
        existsSync(join(ROOT, "app", path === "llms.txt" ? "llms.txt" : path.replace(/\..*$/, ".ts"))),
        `/${path} must be generated by the app, else it proves nothing`,
      ).toBe(true);
    }
  });

  it("never checks a path that exists in public/", () => {
    // The whole failure mode is "public/ is being served instead of the app".
    // Any file under public/ answers 200 in that state.
    const staticFiles = ["mcp.json", "cartwright.png", "docs"];
    for (const file of staticFiles) {
      expect(
        routes,
        `${file} exists in public/ — it answers 200 in exactly the broken state`,
      ).not.toContain(file);
    }
  });
});
